// Code generated by protoc-gen-go. DO NOT EDIT.
// source: gossip.proto

/*
Package gossip is a generated protocol buffer package.

It is generated from these files:
	gossip.proto

It has these top-level messages:
	GossipMsg
	Certificate
	Partners
	Accusation
	Note
	Signature
	Data
	Ping
	Pong
*/
package gossip

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type GossipMsg struct {
	Certificates []*Certificate `protobuf:"bytes,1,rep,name=certificates" json:"certificates,omitempty"`
	Notes        []*Note        `protobuf:"bytes,2,rep,name=notes" json:"notes,omitempty"`
	Accusations  []*Accusation  `protobuf:"bytes,3,rep,name=accusations" json:"accusations,omitempty"`
	OwnNote      *Note          `protobuf:"bytes,4,opt,name=ownNote" json:"ownNote,omitempty"`
	Data         []*Data        `protobuf:"bytes,5,rep,name=data" json:"data,omitempty"`
}

func (m *GossipMsg) Reset()                    { *m = GossipMsg{} }
func (m *GossipMsg) String() string            { return proto.CompactTextString(m) }
func (*GossipMsg) ProtoMessage()               {}
func (*GossipMsg) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *GossipMsg) GetCertificates() []*Certificate {
	if m != nil {
		return m.Certificates
	}
	return nil
}

func (m *GossipMsg) GetNotes() []*Note {
	if m != nil {
		return m.Notes
	}
	return nil
}

func (m *GossipMsg) GetAccusations() []*Accusation {
	if m != nil {
		return m.Accusations
	}
	return nil
}

func (m *GossipMsg) GetOwnNote() *Note {
	if m != nil {
		return m.OwnNote
	}
	return nil
}

func (m *GossipMsg) GetData() []*Data {
	if m != nil {
		return m.Data
	}
	return nil
}

// Raw certificate
type Certificate struct {
	Raw []byte `protobuf:"bytes,1,opt,name=raw,proto3" json:"raw,omitempty"`
}

func (m *Certificate) Reset()                    { *m = Certificate{} }
func (m *Certificate) String() string            { return proto.CompactTextString(m) }
func (*Certificate) ProtoMessage()               {}
func (*Certificate) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *Certificate) GetRaw() []byte {
	if m != nil {
		return m.Raw
	}
	return nil
}

// Only populated if not a valid neighbor
type Partners struct {
	Certificates []*Certificate `protobuf:"bytes,1,rep,name=certificates" json:"certificates,omitempty"`
	Notes        []*Note        `protobuf:"bytes,2,rep,name=Notes" json:"Notes,omitempty"`
}

func (m *Partners) Reset()                    { *m = Partners{} }
func (m *Partners) String() string            { return proto.CompactTextString(m) }
func (*Partners) ProtoMessage()               {}
func (*Partners) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *Partners) GetCertificates() []*Certificate {
	if m != nil {
		return m.Certificates
	}
	return nil
}

func (m *Partners) GetNotes() []*Note {
	if m != nil {
		return m.Notes
	}
	return nil
}

// accuser and accused are the respective node ids
type Accusation struct {
	Epoch     uint64     `protobuf:"varint,1,opt,name=epoch" json:"epoch,omitempty"`
	Accuser   []byte     `protobuf:"bytes,2,opt,name=accuser,proto3" json:"accuser,omitempty"`
	Accused   []byte     `protobuf:"bytes,3,opt,name=accused,proto3" json:"accused,omitempty"`
	Signature *Signature `protobuf:"bytes,4,opt,name=signature" json:"signature,omitempty"`
	Mask      []byte     `protobuf:"bytes,5,opt,name=mask,proto3" json:"mask,omitempty"`
	RingNum   uint32     `protobuf:"varint,6,opt,name=ringNum" json:"ringNum,omitempty"`
}

func (m *Accusation) Reset()                    { *m = Accusation{} }
func (m *Accusation) String() string            { return proto.CompactTextString(m) }
func (*Accusation) ProtoMessage()               {}
func (*Accusation) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *Accusation) GetEpoch() uint64 {
	if m != nil {
		return m.Epoch
	}
	return 0
}

func (m *Accusation) GetAccuser() []byte {
	if m != nil {
		return m.Accuser
	}
	return nil
}

func (m *Accusation) GetAccused() []byte {
	if m != nil {
		return m.Accused
	}
	return nil
}

func (m *Accusation) GetSignature() *Signature {
	if m != nil {
		return m.Signature
	}
	return nil
}

func (m *Accusation) GetMask() []byte {
	if m != nil {
		return m.Mask
	}
	return nil
}

func (m *Accusation) GetRingNum() uint32 {
	if m != nil {
		return m.RingNum
	}
	return 0
}

type Note struct {
	Epoch     uint64     `protobuf:"varint,1,opt,name=epoch" json:"epoch,omitempty"`
	Id        []byte     `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	Mask      []byte     `protobuf:"bytes,3,opt,name=mask,proto3" json:"mask,omitempty"`
	Signature *Signature `protobuf:"bytes,4,opt,name=signature" json:"signature,omitempty"`
}

func (m *Note) Reset()                    { *m = Note{} }
func (m *Note) String() string            { return proto.CompactTextString(m) }
func (*Note) ProtoMessage()               {}
func (*Note) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *Note) GetEpoch() uint64 {
	if m != nil {
		return m.Epoch
	}
	return 0
}

func (m *Note) GetId() []byte {
	if m != nil {
		return m.Id
	}
	return nil
}

func (m *Note) GetMask() []byte {
	if m != nil {
		return m.Mask
	}
	return nil
}

func (m *Note) GetSignature() *Signature {
	if m != nil {
		return m.Signature
	}
	return nil
}

// Raw elliptic signature
type Signature struct {
	R []byte `protobuf:"bytes,1,opt,name=r,proto3" json:"r,omitempty"`
	S []byte `protobuf:"bytes,2,opt,name=s,proto3" json:"s,omitempty"`
}

func (m *Signature) Reset()                    { *m = Signature{} }
func (m *Signature) String() string            { return proto.CompactTextString(m) }
func (*Signature) ProtoMessage()               {}
func (*Signature) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *Signature) GetR() []byte {
	if m != nil {
		return m.R
	}
	return nil
}

func (m *Signature) GetS() []byte {
	if m != nil {
		return m.S
	}
	return nil
}

type Data struct {
	Content []byte `protobuf:"bytes,1,opt,name=content,proto3" json:"content,omitempty"`
	Id      []byte `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
}

func (m *Data) Reset()                    { *m = Data{} }
func (m *Data) String() string            { return proto.CompactTextString(m) }
func (*Data) ProtoMessage()               {}
func (*Data) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *Data) GetContent() []byte {
	if m != nil {
		return m.Content
	}
	return nil
}

func (m *Data) GetId() []byte {
	if m != nil {
		return m.Id
	}
	return nil
}

type Ping struct {
	Nonce []byte `protobuf:"bytes,1,opt,name=nonce,proto3" json:"nonce,omitempty"`
}

func (m *Ping) Reset()                    { *m = Ping{} }
func (m *Ping) String() string            { return proto.CompactTextString(m) }
func (*Ping) ProtoMessage()               {}
func (*Ping) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func (m *Ping) GetNonce() []byte {
	if m != nil {
		return m.Nonce
	}
	return nil
}

type Pong struct {
	Nonce     []byte     `protobuf:"bytes,1,opt,name=nonce,proto3" json:"nonce,omitempty"`
	Signature *Signature `protobuf:"bytes,2,opt,name=signature" json:"signature,omitempty"`
}

func (m *Pong) Reset()                    { *m = Pong{} }
func (m *Pong) String() string            { return proto.CompactTextString(m) }
func (*Pong) ProtoMessage()               {}
func (*Pong) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

func (m *Pong) GetNonce() []byte {
	if m != nil {
		return m.Nonce
	}
	return nil
}

func (m *Pong) GetSignature() *Signature {
	if m != nil {
		return m.Signature
	}
	return nil
}

func init() {
	proto.RegisterType((*GossipMsg)(nil), "GossipMsg")
	proto.RegisterType((*Certificate)(nil), "Certificate")
	proto.RegisterType((*Partners)(nil), "Partners")
	proto.RegisterType((*Accusation)(nil), "Accusation")
	proto.RegisterType((*Note)(nil), "Note")
	proto.RegisterType((*Signature)(nil), "Signature")
	proto.RegisterType((*Data)(nil), "Data")
	proto.RegisterType((*Ping)(nil), "Ping")
	proto.RegisterType((*Pong)(nil), "Pong")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Gossip service

type GossipClient interface {
	Spread(ctx context.Context, in *GossipMsg, opts ...grpc.CallOption) (*Partners, error)
}

type gossipClient struct {
	cc *grpc.ClientConn
}

func NewGossipClient(cc *grpc.ClientConn) GossipClient {
	return &gossipClient{cc}
}

func (c *gossipClient) Spread(ctx context.Context, in *GossipMsg, opts ...grpc.CallOption) (*Partners, error) {
	out := new(Partners)
	err := grpc.Invoke(ctx, "/gossip/Spread", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Gossip service

type GossipServer interface {
	Spread(context.Context, *GossipMsg) (*Partners, error)
}

func RegisterGossipServer(s *grpc.Server, srv GossipServer) {
	s.RegisterService(&_Gossip_serviceDesc, srv)
}

func _Gossip_Spread_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GossipMsg)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GossipServer).Spread(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/gossip/Spread",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GossipServer).Spread(ctx, req.(*GossipMsg))
	}
	return interceptor(ctx, in, info, handler)
}

var _Gossip_serviceDesc = grpc.ServiceDesc{
	ServiceName: "gossip",
	HandlerType: (*GossipServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Spread",
			Handler:    _Gossip_Spread_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "gossip.proto",
}

func init() { proto.RegisterFile("gossip.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 402 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x53, 0xcd, 0x8a, 0xd5, 0x30,
	0x18, 0x35, 0x6d, 0x7a, 0xc7, 0x7e, 0xad, 0x22, 0xc1, 0x45, 0xfc, 0x81, 0xa9, 0xd9, 0x58, 0x10,
	0xcb, 0x30, 0x3e, 0x81, 0x28, 0xba, 0xf2, 0x72, 0xc9, 0xac, 0x5c, 0xc6, 0x36, 0xd6, 0x28, 0x93,
	0x94, 0x24, 0x97, 0x79, 0x2b, 0xdf, 0xc2, 0xf7, 0x92, 0xa4, 0xbf, 0x23, 0x57, 0x91, 0xd9, 0xf5,
	0x9c, 0xef, 0x70, 0x72, 0x4e, 0xd2, 0x0f, 0xca, 0xde, 0x38, 0xa7, 0x86, 0x66, 0xb0, 0xc6, 0x1b,
	0xf6, 0x0b, 0x41, 0xfe, 0x31, 0x12, 0x9f, 0x5c, 0x4f, 0x2e, 0xa0, 0x6c, 0xa5, 0xf5, 0xea, 0xab,
	0x6a, 0x85, 0x97, 0x8e, 0xa2, 0x2a, 0xad, 0x8b, 0xcb, 0xb2, 0x79, 0xb7, 0x92, 0xfc, 0x96, 0x82,
	0x3c, 0x83, 0x4c, 0x9b, 0x20, 0x4d, 0xa2, 0x34, 0x6b, 0xf6, 0xc6, 0x4b, 0x3e, 0x72, 0xe4, 0x35,
	0x14, 0xa2, 0x6d, 0x8f, 0x4e, 0x78, 0x65, 0xb4, 0xa3, 0x69, 0x94, 0x14, 0xcd, 0xdb, 0x85, 0xe3,
	0xdb, 0x39, 0x39, 0x87, 0x33, 0x73, 0xa3, 0x83, 0x01, 0xc5, 0x15, 0x5a, 0xdd, 0x66, 0x96, 0x3c,
	0x01, 0xdc, 0x09, 0x2f, 0x68, 0x36, 0x9d, 0xf5, 0x5e, 0x78, 0xc1, 0x23, 0xc5, 0xce, 0xa1, 0xd8,
	0x84, 0x24, 0x8f, 0x20, 0xb5, 0xe2, 0x86, 0xa2, 0x0a, 0xd5, 0x25, 0x0f, 0x9f, 0xec, 0x33, 0xdc,
	0x3f, 0x08, 0xeb, 0xb5, 0xb4, 0xee, 0x6e, 0x35, 0xf7, 0x27, 0x6a, 0x46, 0x8e, 0xfd, 0x44, 0x00,
	0x6b, 0x27, 0xf2, 0x18, 0x32, 0x39, 0x98, 0xf6, 0x5b, 0x3c, 0x1d, 0xf3, 0x11, 0x10, 0x0a, 0x67,
	0xb1, 0xab, 0xb4, 0x34, 0x89, 0xa9, 0x66, 0xb8, 0x4e, 0x3a, 0x9a, 0x6e, 0x27, 0x1d, 0xa9, 0x21,
	0x77, 0xaa, 0xd7, 0xc2, 0x1f, 0xed, 0x7c, 0x25, 0xd0, 0x5c, 0xcd, 0x0c, 0x5f, 0x87, 0x84, 0x00,
	0xbe, 0x16, 0xee, 0x07, 0xcd, 0xa2, 0x41, 0xfc, 0x0e, 0xbe, 0x56, 0xe9, 0x7e, 0x7f, 0xbc, 0xa6,
	0xbb, 0x0a, 0xd5, 0x0f, 0xf8, 0x0c, 0xd9, 0x77, 0xc0, 0xf1, 0x3e, 0x4f, 0x27, 0x7d, 0x08, 0x89,
	0xea, 0xa6, 0x90, 0x89, 0xea, 0x16, 0xef, 0x74, 0xe3, 0xfd, 0xdf, 0xc9, 0xd8, 0x4b, 0xc8, 0x17,
	0x9e, 0x94, 0x80, 0xec, 0xf4, 0x28, 0xc8, 0x06, 0xe4, 0xa6, 0x73, 0x90, 0x63, 0x17, 0x80, 0xc3,
	0x7b, 0x86, 0xd8, 0xad, 0xd1, 0x5e, 0x6a, 0x3f, 0x29, 0x67, 0xf8, 0x67, 0x30, 0xf6, 0x1c, 0xf0,
	0x41, 0xe9, 0x3e, 0xd4, 0xd0, 0x46, 0xb7, 0x72, 0xd2, 0x8f, 0x80, 0x7d, 0x00, 0x7c, 0x30, 0x7f,
	0x9b, 0xde, 0x2e, 0x90, 0xfc, 0xa3, 0xc0, 0xe5, 0x2b, 0xd8, 0x8d, 0x1b, 0x43, 0x5e, 0xc0, 0xee,
	0x6a, 0xb0, 0x52, 0x74, 0x04, 0x9a, 0x65, 0x67, 0x9e, 0xe6, 0xcd, 0xfc, 0x5f, 0xb1, 0x7b, 0x5f,
	0x76, 0x71, 0xab, 0xde, 0xfc, 0x0e, 0x00, 0x00, 0xff, 0xff, 0x3f, 0x81, 0xce, 0x00, 0x65, 0x03,
	0x00, 0x00,
}
